[font]
size = 10.0
normal = { family = "Cousine Nerd Font Mono", style = "Regular" }

[general]
import = [
  # uncomment the flavour you want below:
  # "~/.config/alacritty/catppuccin-latte.toml"
  "~/.config/alacritty/catppuccin-frappe.toml"
  # "~/.config/alacritty/catppuccin-macchiato.toml"
  # "~/.config/alacritty/catppuccin-mocha.toml"
]
